import { initScene } from './scene.js';
import { initScroll } from './scroll.js';
import { initNav } from './nav.js';
import { initTilt } from './tilt.js';

const garments={
 puffer:{name:'Puffer Jacket',collection:'WINTER 2026',tags:['Oversized','Quilted','Sustainable'],description:'A bold statement in premium recycled fill, this oversized puffer commands attention without compromise. The exaggerated silhouette softens under movement, creating a fluid drama that follows you through the city.',details:[['ruler','Length','85cm'],['snow','Fill Power','800FP Duck Down'],['leaf','Material','Recycled Ripstop Nylon'],['size','Sizes','XS – 3XL']],note:'Perfect from urban commute to mountain getaway.',caption:'When warmth becomes a statement.',close:'The quilted baffles follow the body’s natural curves, creating a geometric relief that catches light from every angle.',lens:'40% 25%',feature:'The bold puffer.',featureText:'Recycled fill. Maximum warmth. Minimum impact.'},
 trench:{name:'Trench Coat',collection:'SS 2026',tags:['Classic','Belted','Versatile'],description:'Reimagined in a fluid camel wool blend, this trench moves between seasons without effort. Double-breasted with a self-belt that cinches or floats — the choice is always yours.',details:[['ruler','Length','112cm'],['fabric','Fabric','Italian Wool Blend'],['star','Lining','Silk Touch Polyester'],['size','Sizes','XS – 2XL']],note:'The bridge between sharp tailoring and effortless elegance.',caption:'Some coats tell a story. This one writes it.',close:'The hand-stitched lapels carry a subtle sheen — the kind you notice only in movement.',lens:'55% 18%',feature:'Tailored forever.',featureText:'Italian wool. Fluid silhouette. Every season.'}
};
const icon=id=>`<svg aria-hidden="true"><use href="#i-${id}"></use></svg>`;
const article=document.querySelector('#detail-content'),caption=document.querySelector('#caption');let current='puffer';
function renderDetails(id,animate=true){const d=garments[id];article.classList.remove('detail-anim-in');article.innerHTML=`<p class="eyebrow">${d.collection} · WOMENSWEAR</p><h1>${d.name}</h1><div class="tag-row">${d.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><p class="detail-desc">${d.description}</p><h2>Key Details</h2><div class="traits">${d.details.map(([ic,label,value])=>`<div class="trait">${icon(ic)}<small>${label}</small><span>${value}</span></div>`).join('')}</div><h2>Style Notes</h2><p class="note">${icon('star')}<span>${d.note}</span></p><button class="close-up" id="close-up" aria-pressed="false"><span class="lens" style="background-image:linear-gradient(135deg,rgba(255,255,255,.24),rgba(255,45,120,.28)),linear-gradient(115deg,${id==='puffer'?'#ff8ab1,#ff2d78,#67133d':'#f0dcb7,#c8a97e,#55432c'});background-position:${d.lens}"></span><span><strong>Close-up Detail</strong><p>${d.close}</p></span>${icon('chevron')}</button>`;
 caption.textContent=d.caption;document.querySelector('#featured-title').textContent=d.feature;document.querySelector('#featured-desc').textContent=d.featureText;
 if(animate){article.classList.add('detail-anim-in');[...article.children].forEach((el,i)=>el.style.animationDelay=`${i*45}ms`);}
 article.querySelector('#close-up').addEventListener('click',e=>{const pressed=e.currentTarget.getAttribute('aria-pressed')==='true';scene.setZoom(pressed?1:2.6);e.currentTarget.setAttribute('aria-pressed',String(!pressed));});
}
const scene=initScene(document.querySelector('#gl'),document.querySelector('.hero'),document.querySelector('#stage'));
renderDetails(current,false);
const tabs=[...document.querySelectorAll('.tab')];
function select(id){if(id===current)return;const old=article.children;[...old].forEach(el=>{el.style.transition='opacity .2s ease,transform .2s ease';el.style.opacity='0';el.style.transform='translateY(-6px)';});window.setTimeout(()=>{current=id;scene.switchItem(id);tabs.forEach(tab=>{const selected=tab.dataset.item===id;tab.classList.toggle('selected',selected);tab.setAttribute('aria-selected',String(selected));});renderDetails(id,true);},matchMedia('(prefers-reduced-motion: reduce)').matches?0:180);}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>select(tab.dataset.item));tab.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=tabs[(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];next.focus();select(next.dataset.item);}});});
document.querySelectorAll('.icon-rail button').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.action;if(action==='zoom-in')scene.setZoom(scene.zoom*1.35);if(action==='zoom-out')scene.setZoom(scene.zoom/1.35);if(action==='expand'){const on=!document.querySelector('.hero').classList.contains('focus');scene.setExpand(on);button.setAttribute('aria-pressed',String(on));}if(action==='light'){const dusk=scene.setLight();button.setAttribute('aria-pressed',String(dusk));}}));
document.querySelectorAll('[data-turn]').forEach(button=>button.addEventListener('click',()=>scene.queueTurn(Number(button.dataset.turn)*Math.PI/2)));
document.querySelector('.turn-pill span').addEventListener('click',()=>scene.queueTurn(Math.PI*2));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){scene.setExpand(false);document.querySelector('[data-action="expand"]').setAttribute('aria-pressed','false');}});
document.querySelectorAll('.cart-button,.quick-add').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.product-card');const add=card?.querySelector('.cart-button');if(add){add.classList.add('added');add.innerHTML='Added to bag <span>✓</span>';window.setTimeout(()=>{add.classList.remove('added');add.innerHTML='Add to Cart <span>+</span>';},1800);}else{button.setAttribute('aria-label','Added to cart');}}));
initNav();initTilt(document.querySelectorAll('[data-tilt]'));initScroll().catch(error=>console.warn('Smooth scroll enhancement unavailable; native page scrolling remains active.',error));
