import {initScene} from './scene.js';import {initScroll} from './scroll.js';import {initNav} from './nav.js';import {initTilt} from './tilt.js';import {initPreloader} from './preloader.js';
const products=[
{id:'cloud-nine',name:'Cloud Nine Puffer',category:'outerwear',material:'Recycled ripstop · Rose quartz',price:420,color:'Rose quartz',img:'photo-1548624149-f0c15a6bb9cf'},
{id:'soft-armour',name:'Soft Armour Trench',category:'outerwear',material:'Italian wool blend · Warm sand',price:680,color:'Warm sand',img:'photo-1539533018447-63fcce2678e3'},
{id:'afterglow',name:'Afterglow Slip Dress',category:'dresses',material:'Responsible satin · Midnight',price:390,color:'Midnight',img:'photo-1539008835657-9e8e9680c956'},
{id:'new-romantic',name:'New Romantic Dress',category:'dresses',material:'Fluid recycled crepe · Petal',price:460,color:'Petal',img:'photo-1595777457583-95e059d581b8'},
{id:'city-shell',name:'City Shell Jacket',category:'outerwear',material:'Plant-based performance · Moss',price:510,color:'Moss',img:'photo-1544923246-77307dd654cb'},
{id:'kinetic-knit',name:'Kinetic Knit',category:'dresses',material:'Traceable merino · Electric blue',price:280,color:'Electric blue',img:'photo-1566206091558-7f218b696731'},
{id:'golden-hour',name:'Golden Hour Blazer',category:'outerwear',material:'Deadstock tailoring · Sunlit gold',price:590,color:'Sunlit gold',img:'photo-1591047139829-d91aecb6caea'},
{id:'form-scarf',name:'Form Study Scarf',category:'accessories',material:'Brushed cashmere · Ink',price:165,color:'Ink',img:'photo-1601924994987-69e26d50dc26'},
{id:'lumiere-carryall',name:'Lumière Carryall',category:'accessories',material:'LWG grain leather · Espresso',price:540,color:'Espresso',img:'photo-1584917865442-de89df76afd3'},
{id:'orbit-earrings',name:'Orbit Earrings',category:'accessories',material:'Recycled vermeil · Liquid gold',price:125,color:'Liquid gold',img:'photo-1535632066927-ab7c9ab60908'}];
const money=n=>'$'+n.toLocaleString('en-US');const grid=document.querySelector('#product-grid');let filter='all',query='';let cart=0;try{cart=Number(sessionStorage.getItem('lumiere-cart')||0)}catch{}document.querySelectorAll('.cart-count').forEach(e=>e.textContent=cart);
function renderProducts(){const shown=products.filter(p=>(filter==='all'||p.category===filter)&&(p.name+' '+p.material+' '+p.category).toLowerCase().includes(query));grid.innerHTML=shown.map((p,i)=>`<article class="product-card" data-tilt data-category="${p.category}"><div class="product-image"><img src="https://images.unsplash.com/${p.img}?w=800&q=80" alt="${p.name}, ${p.color}" loading="lazy"><span class="product-index">L / ${String(products.indexOf(p)+1).padStart(2,'0')}</span><button class="quick-add" type="button" data-add="${p.id}" aria-label="Add ${p.name} to bag">+</button></div><div class="product-info"><div><h3>${p.name}</h3><p>${p.material}</p><p class="product-category">${p.category}</p></div><strong>${money(p.price)}</strong></div></article>`).join('')||'<p class="empty-state">No pieces found. Try another search.</p>';initTilt(grid.querySelectorAll('[data-tilt]'));}
renderProducts();grid.addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(!b)return;cart++;document.querySelectorAll('.cart-count').forEach(x=>x.textContent=cart);try{sessionStorage.setItem('lumiere-cart',cart)}catch{}b.textContent='✓';b.setAttribute('aria-label','Added to bag');setTimeout(()=>{b.textContent='+';b.setAttribute('aria-label','Add item to bag')},1100)});
document.querySelectorAll('.filter-chip').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('.filter-chip').forEach(x=>x.classList.toggle('active',x===b));renderProducts()}));document.querySelector('#product-search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();renderProducts()});
const scene=initScene(document.querySelector('#gl'));document.querySelector('#scene-loader').classList.add('hidden');document.querySelectorAll('.outfit-tab').forEach(b=>b.addEventListener('click',()=>{scene.switchOutfit(b.dataset.outfit);document.querySelectorAll('.outfit-tab').forEach(x=>{x.classList.toggle('is-active',x===b);x.setAttribute('aria-selected',String(x===b))})}));document.querySelectorAll('[data-scene-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.sceneAction;if(a==='zoom-in')scene.setZoom(scene.zoom*1.2);if(a==='zoom-out')scene.setZoom(scene.zoom/1.2);if(a==='light')scene.setLight()}));
const worlds=[...document.querySelectorAll('.world-panel')],dots=[...document.querySelectorAll('.world-dots button')];let activeWorld=0;function showWorld(i){activeWorld=(i+worlds.length)%worlds.length;worlds.forEach((w,n)=>w.classList.toggle('is-active',n===activeWorld));dots.forEach((d,n)=>d.classList.toggle('active',n===activeWorld));document.querySelector('#world-current').textContent=String(activeWorld+1).padStart(2,'0')}document.querySelector('#world-next').addEventListener('click',()=>showWorld(activeWorld+1));document.querySelector('#world-prev').addEventListener('click',()=>showWorld(activeWorld-1));dots.forEach((d,i)=>d.addEventListener('click',()=>showWorld(i)));let touchX=0;document.querySelector('.world-stage').addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});document.querySelector('.world-stage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>55)showWorld(activeWorld+(dx<0?1:-1))},{passive:true});
const form=document.querySelector('#newsletter-form'),message=document.querySelector('#newsletter-message');form.addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#email');if(!input.validity.valid){input.reportValidity();return}message.textContent='You’re on the list. Watch your inbox for a little light ✳';message.style.color='var(--cyan)';form.reset()});
document.querySelector('.theme-toggle').addEventListener('click',()=>{const root=document.documentElement;root.dataset.theme=root.dataset.theme==='dark'?'light':'dark'});
initNav();initPreloader();initScroll(scene).catch(e=>console.warn('Scroll enhancement unavailable; native scrolling is active.',e));
