/* LUMIÈRE real-time scene — Three.js r160 */
import * as THREE from 'three';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/GLTFLoader.js';
(() => {
'use strict';
const canvas=document.querySelector('#world'); if(!canvas)return;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x0D0B1A); scene.fog=new THREE.FogExp2(0x0D0B1A,.012);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,220); camera.position.set(0,0,5);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.25;
scene.add(new THREE.AmbientLight(0x9daaff,.7)); const key=new THREE.PointLight(0xff2d78,30,38);key.position.set(-4,3,-25);scene.add(key); const fill=new THREE.PointLight(0x00f5ff,24,38);fill.position.set(5,1,-61);scene.add(fill);
const worlds=[];
function group(z){const g=new THREE.Group();g.position.z=z;scene.add(g);worlds.push(g);return g}
function particles(parent,count,radius,colors,centerZ=0){const positions=new Float32Array(count*3),cols=new Float32Array(count*3);const c=colors.map(x=>new THREE.Color(x));for(let i=0;i<count;i++){const u=Math.random()*2-1,a=Math.random()*Math.PI*2,r=radius*Math.cbrt(Math.random()),s=Math.sqrt(1-u*u);positions[i*3]=r*s*Math.cos(a);positions[i*3+1]=r*u;positions[i*3+2]=r*s*Math.sin(a)+centerZ;const color=c[Math.random()<.68?0:1];cols[i*3]=color.r;cols[i*3+1]=color.g;cols[i*3+2]=color.b}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(cols,3));const mat=new THREE.PointsMaterial({size:.075,vertexColors:true,transparent:true,opacity:.88,blending:THREE.AdditiveBlending,depthWrite:false});const p=new THREE.Points(geo,mat);parent.add(p);return p}
// World 0: 2,000 jewel-like sphere particles.
const portal=group(0);const portalDust=particles(portal,2000,11,[0xff2d78,0x00f5ff]);
for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(5.5+i*1.3,.012,6,150),new THREE.MeshBasicMaterial({color:i%2?0x00f5ff:0xff2d78,transparent:true,opacity:.3}));ring.position.z=-7-i*.06;ring.rotation.x=(i-1)*.22;portal.add(ring)}
// World 1: runway hall, luminous architecture, mannequin assembled from primitives.
const hall=group(-30);const neonPink=new THREE.MeshStandardMaterial({color:0x180b21,emissive:0xff2d78,emissiveIntensity:2.2,metalness:.5,roughness:.25});const neonCyan=new THREE.MeshStandardMaterial({color:0x091a25,emissive:0x00f5ff,emissiveIntensity:1.8,metalness:.4,roughness:.3});const dark=new THREE.MeshStandardMaterial({color:0x151126,metalness:.45,roughness:.5});
const floor=new THREE.Mesh(new THREE.BoxGeometry(12,.22,34),dark);floor.position.set(0,-3,-11);hall.add(floor);const runway=new THREE.Mesh(new THREE.BoxGeometry(3,.08,30),new THREE.MeshStandardMaterial({color:0x231127,emissive:0xff2d78,emissiveIntensity:.22,metalness:.2,roughness:.3}));runway.position.set(0,-2.86,-11);hall.add(runway);
for(const x of [-6,6]){const wall=new THREE.Mesh(new THREE.BoxGeometry(.18,9,34),dark);wall.position.set(x,1,-11);hall.add(wall);const strip=new THREE.Mesh(new THREE.BoxGeometry(.07,.08,33),x<0?neonPink:neonCyan);strip.position.set(x*.96,3.6,-11);hall.add(strip)}
for(let i=0;i<10;i++){let z=2-i*3.1;for(const x of [-5.7,5.7]){const col=new THREE.Mesh(new THREE.BoxGeometry(.12,5,.12),i%2?neonCyan:neonPink);col.position.set(x,-.5,z);hall.add(col);const cap=new THREE.Mesh(new THREE.SphereGeometry(.15,12,8),i%2?neonCyan:neonPink);cap.position.set(x,2.1,z);hall.add(cap)}}
// Three spotlights / columns, with actual lights for cinematic highlights.
for(const x of [-3.8,0,3.8]){const spot=new THREE.SpotLight(x===0?0xff2d78:0x00f5ff,90,22,Math.PI/7,.55,1.4);spot.position.set(x,5,-7);spot.target.position.set(0,-2,-10);hall.add(spot,spot.target);const beam=new THREE.Mesh(new THREE.CylinderGeometry(.03,1.5,8,20,1,true),new THREE.MeshBasicMaterial({color:x===0?0xff2d78:0x00f5ff,transparent:true,opacity:.055,side:THREE.DoubleSide,depthWrite:false}));beam.position.set(x,1,-8);hall.add(beam)}
const mannequin=new THREE.Group();mannequin.position.set(0,-2.5,-8);hall.add(mannequin);const skin=new THREE.MeshStandardMaterial({color:0xd7b6c6,metalness:.35,roughness:.28}),cloth=new THREE.MeshStandardMaterial({color:0x20162a,emissive:0x5a1033,emissiveIntensity:.4,metalness:.45,roughness:.3});function part(geo,mat,x,y,z,sx=1,sy=1,sz=1){const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);mannequin.add(m);return m}
part(new THREE.SphereGeometry(.42,24,18),skin,0,2.95,0,.77,1.08,.72);part(new THREE.CylinderGeometry(.13,.16,.42,16),skin,0,2.45,0);part(new THREE.SphereGeometry(.24,18,12),skin,0,2.12,0,1.4,.72,.8);part(new THREE.CylinderGeometry(.35,.5,1.05,12),cloth,0,1.35,0,1.15,1,.7);part(new THREE.SphereGeometry(.31,16,12),cloth,0,.73,0,1.25,.8,.72);
for(const side of [-1,1]){const arm=part(new THREE.CylinderGeometry(.11,.16,1.12,12),skin,side*.55,1.62,0);arm.rotation.z=side*.22;part(new THREE.SphereGeometry(.13,12,8),skin,side*.68,1.03,0);const leg=part(new THREE.CylinderGeometry(.13,.19,1.2,12),cloth,side*.2,.03,0);leg.rotation.z=side*.03;part(new THREE.BoxGeometry(.28,.14,.48),skin,side*.2,-.65,.1)}
const gltfLoader=new GLTFLoader();let modelMixer=null;const modelStatus={loaded:false,error:null};if(gltfLoader){gltfLoader.load('https://threejs.org/examples/models/gltf/Soldier.glb',g=>{const model=g.scene;model.scale.setScalar(1.7);model.position.set(2.25,-2.8,-9);model.rotation.y=-.32;hall.add(model);if(g.animations&&g.animations.length){modelMixer=new THREE.AnimationMixer(model);modelMixer.clipAction(g.animations[0]).play()}modelStatus.loaded=true;},undefined,e=>{modelStatus.error=e;console.warn('GLTF placeholder failed to load; procedural mannequin remains active.',e)})}
// World 2: twelve floating product panels, deliberately abstract and editable.
const collection=group(-60);const cardMaterials=[new THREE.MeshBasicMaterial({color:0x291024,side:THREE.DoubleSide}),new THREE.MeshBasicMaterial({color:0x10252a,side:THREE.DoubleSide}),new THREE.MeshBasicMaterial({color:0x25203b,side:THREE.DoubleSide})];const cards=[];for(let i=0;i<12;i++){const card=new THREE.Mesh(new THREE.PlaneGeometry(1.55,2.15),cardMaterials[i%3]);const angle=i/12*Math.PI*2;card.position.set(Math.cos(angle)*4.5,(Math.random()-.5)*4,Math.sin(angle)*5-1);card.rotation.y=(Math.random()-.5)*.65;card.rotation.x=(Math.random()-.5)*.2;collection.add(card);const frame=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.PlaneGeometry(1.58,2.18)),new THREE.LineBasicMaterial({color:i%3===0?0xff2d78:i%3===1?0x00f5ff:0xaaff00,transparent:true,opacity:.8}));card.add(frame);const emblem=new THREE.Mesh(new THREE.TorusGeometry(.35,.045,8,36),new THREE.MeshBasicMaterial({color:i%2?0x00f5ff:0xff2d78}));emblem.position.z=.02;card.add(emblem);cards.push(card)}
// World 3: quiet reflective particle field.
const finale=group(-90);const calmDust=particles(finale,1000,14,[0x00f5ff,0xaaff00]);for(let i=0;i<4;i++){const mirror=new THREE.Mesh(new THREE.PlaneGeometry(13,8),new THREE.MeshBasicMaterial({color:i%2?0x00f5ff:0xaaff00,transparent:true,opacity:.018,side:THREE.DoubleSide}));mirror.position.set(i%2?6:-6,0,-4-i*4);mirror.rotation.y=i%2?-.4:.4;finale.add(mirror)}
const clock=new THREE.Clock();function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight)}addEventListener('resize',resize,{passive:true});function render(){requestAnimationFrame(render);const t=clock.getElapsedTime(),dt=Math.min(clock.getDelta(),.05);portalDust.rotation.y=t*.018;portalDust.rotation.x=Math.sin(t*.12)*.035;calmDust.rotation.y=t*.012;calmDust.rotation.x=t*.006;cards.forEach((c,i)=>{c.rotation.y+=Math.sin(t*.35+i)*.0007;c.position.y+=Math.sin(t*.6+i)*.001});mannequin.rotation.y=Math.sin(t*.5)*.08;if(modelMixer)modelMixer.update(dt);key.intensity=26+Math.sin(t*1.2)*5;renderer.render(scene,camera)}render();
window.LumiereScene={scene,camera,renderer,worlds,cards,modelStatus,resize};window.dispatchEvent(new Event('lumiere:scene-ready'));
})();