import * as THREE from 'three';
// Lightweight procedural couture forms keep the viewer self-contained and CDN-only.
const COLORS={puffer:'#ee318b',trench:'#c6a06a',gala:'#28c9c1'};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function mannequin(kind){const g=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color:COLORS[kind],roughness:kind==='gala'?.28:.58,metalness:kind==='gala'?.42:.08}),dark=new THREE.MeshStandardMaterial({color:'#242330',roughness:.7}),skin=new THREE.MeshStandardMaterial({color:'#d6b7a1',roughness:.72}),gold=new THREE.MeshStandardMaterial({color:'#e7bc63',metalness:.75,roughness:.24});const add=(geo,mat,pos,scale)=>{const m=new THREE.Mesh(geo,mat);m.position.set(...pos);if(scale)m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;g.add(m);return m};
 add(new THREE.SphereGeometry(.16,20,16),skin,[0,1.35,0],[.8,1.15,.8]);add(new THREE.CylinderGeometry(.07,.08,.22,12),skin,[0,1.13,0]);add(new THREE.CapsuleGeometry(.28,.56,6,12),dark,[0,.24,0],[1,.9,.7]);
 for(const s of [-1,1]){const leg=add(new THREE.CylinderGeometry(.09,.07,.8,12),dark,[s*.13,-.38,0]);leg.rotation.z=s*.015;add(new THREE.SphereGeometry(.1,12,10),dark,[s*.13,-.8,.04],[1,.5,1.5]);const arm=add(new THREE.CapsuleGeometry(.085,.57,5,10),cloth,[s*.43,.61,0]);arm.rotation.z=s*-.22;add(new THREE.SphereGeometry(.065,10,8),skin,[s*.48,.2,.02]);}
 if(kind==='puffer'){add(new THREE.CylinderGeometry(.38,.33,.92,32,9,true),cloth,[0,.53,0]);for(let y=.12;y<.99;y+=.16){const tor=add(new THREE.TorusGeometry(.365-(y-.12)*.045,.018,5,32),gold,[0,y,0]);tor.rotation.x=Math.PI/2;}add(new THREE.TorusGeometry(.16,.055,8,24),cloth,[0,1.02,0]).rotation.x=Math.PI/2;}
 else if(kind==='trench'){add(new THREE.CylinderGeometry(.32,.46,1.5,32,2,true),cloth,[0,.26,0]);add(new THREE.TorusGeometry(.34,.035,7,40),gold,[0,.48,.03]).rotation.x=Math.PI/2;add(new THREE.BoxGeometry(.11,.1,.035),gold,[.08,.48,.36]);for(const s of [-1,1]){const lap=add(new THREE.BufferGeometry(),gold,[0,0,0]);lap.geometry.setAttribute('position',new THREE.Float32BufferAttribute([s*.01,1.4,.2,s*.27,1.3,.22,s*.1,.83,.24],3));lap.geometry.setIndex([0,1,2]);lap.geometry.computeVertexNormals();lap.material.side=THREE.DoubleSide;}}
 else{const dress=add(new THREE.ConeGeometry(.53,1.45,32,1,true),cloth,[0,.34,0]);dress.rotation.x=Math.PI;add(new THREE.TorusGeometry(.42,.035,8,36),gold,[0,.86,.02]).rotation.x=Math.PI/2;for(let i=0;i<9;i++){const bead=add(new THREE.SphereGeometry(.018,8,8),gold,[(Math.random()-.5)*.45,.95+Math.random()*.5,.18]);}}
 add(new THREE.CylinderGeometry(.21,.25,.1,20),cloth,[0,1.03,0]);return g;}
export function initScene(canvas){const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#faf7f9',.04);const camera=new THREE.PerspectiveCamera(32,1,.1,60);camera.position.set(0,.35,6.3);const ambient=new THREE.HemisphereLight('#fff2f8','#a499ac',2.1);scene.add(ambient);const key=new THREE.DirectionalLight('#fff1dc',3.2);key.position.set(3,5,5);scene.add(key);const pink=new THREE.PointLight('#ff2195',17,9);pink.position.set(-2,1.6,2);scene.add(pink);const cyan=new THREE.PointLight('#18d5cb',12,8);cyan.position.set(2,-.3,-2);scene.add(cyan);const rim=new THREE.DirectionalLight('#ffffff',1.3);rim.position.set(-3,2,-4);scene.add(rim);
 const rigs={};for(const id of Object.keys(COLORS)){const pivot=new THREE.Group();pivot.add(mannequin(id));pivot.visible=false;scene.add(pivot);rigs[id]=pivot;}const particles=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:'#ee318b',size:.018,transparent:true,opacity:.7}));const arr=new Float32Array(450*3);for(let i=0;i<450;i++){arr[i*3]=(Math.random()-.5)*8;arr[i*3+1]=(Math.random()-.5)*5;arr[i*3+2]=(Math.random()-.5)*7;}particles.geometry.setAttribute('position',new THREE.BufferAttribute(arr,3));scene.add(particles);
 let current='puffer',zoom=1,targetZoom=1,drag=false,last=null,spin=0,turn=0,dusk=false,disposed=false;rigs[current].visible=true;const resize=()=>{const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(canvas);resize();canvas.addEventListener('pointerdown',e=>{drag=true;last=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag&&last){spin+=(e.clientX-last[0])*.009;rigs[current].rotation.x=clamp(rigs[current].rotation.x+(e.clientY-last[1])*.004,-.55,.55);last=[e.clientX,e.clientY]}});const end=()=>{drag=false;last=null};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(targetZoom*Math.exp(-e.deltaY*.001))},{passive:false});
 function setZoom(v){targetZoom=clamp(v,.72,1.65)}function switchOutfit(id){if(!rigs[id]||id===current)return;rigs[current].visible=false;current=id;rigs[id].visible=true;rigs[id].rotation.set(0,spin,0);document.querySelector('#outfit-number').textContent=String(Object.keys(rigs).indexOf(id)+1).padStart(2,'0');}
 canvas.addEventListener('dblclick',()=>{targetZoom=1;spin=0;rigs[current].rotation.set(0,0,0)});let prev=performance.now();function animate(now){if(disposed)return;requestAnimationFrame(animate);const dt=Math.min(.05,(now-prev)/1000);prev=now;zoom+=(targetZoom-zoom)*(1-Math.exp(-dt*5));camera.position.z=6.3/zoom;const active=rigs[current];active.rotation.y=spin+Math.sin(now*.00045)*.12;active.position.y=Math.sin(now*.001)*.025;particles.rotation.y+=dt*.025;pink.intensity+=(dusk?26:17-pink.intensity)*(1-Math.exp(-dt*2));renderer.render(scene,camera)}requestAnimationFrame(animate);
 return{switchOutfit,setZoom,get zoom(){return targetZoom},turn(v){spin+=v},setLight(){dusk=!dusk;scene.fog.color.set(dusk?'#161323':'#faf7f9');document.querySelector('.viewer-frame').style.background=dusk?'linear-gradient(140deg,#211b31,#151321)':'';return dusk},setCameraProgress(p){camera.position.x=Math.sin(p*Math.PI*2)*.14;camera.position.y=.35+Math.sin(p*Math.PI)*.18},dispose(){disposed=true;ro.disconnect();renderer.dispose()}};
}
